api_platform:
    title: 'Gobie'
    description: 'API for the Gobie project'
    version: 1.0.0
    show_webby: false
    collection:
        pagination:
            page_parameter_name: p
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
