api_platform:
    title: 'Grooming Chimps'
    description: 'API for the Grooming Chimps project'
    version: 1.0.0
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
