dh_doctrine_audit:
    # Configuration reference available at:
    # https://github.com/DamienHarper/DoctrineAuditBundle#configuration
    table_prefix: ''
    table_suffix: '_audit'
    enabled_viewer: false
    entities:
        App\Entity\Project: ~
        App\Entity\Job: ~
        App\Entity\Task: ~