framework:
    workflows:
        task:
            type: state_machine
            audit_trail:
                enabled: true
            marking_store:
                property: status
            supports:
                - App\Entity\Task
            initial_marking: pending
            places:
                - pending
                - running
                - aborted
                - failed
                - succeeded
            transitions:
                pending_to_running:
                    from: pending
                    to: running
                pending_to_aborted:
                    from: pending
                    to: aborted
                running_to_aborted:
                    from: running
                    to: aborted
                running_to_failed:
                    from: running
                    to: failed
                running_to_succeeded:
                    from: running
                    to: succeeded
        job:
            type: state_machine
            audit_trail:
                enabled: true
            marking_store:
                property: status
            supports:
                - App\Entity\Job
            initial_marking: pending
            places:
                - pending
                - aborted
                - started
                - finished
            transitions:
                pending_to_started:
                    from: pending
                    to: started
                pending_to_aborted:
                    from: pending
                    to: aborted
                started_to_aborted:
                    from: started
                    to: aborted
                started_to_finished:
                    from: started
                    to: finished
                finished_to_pending:
                    from: finished
                    to: pending
                aborted_to_pending:
                    from: aborted
                    to: pending
