image: php:7.3.11

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update
            - apt-get install -y openssh-client
            - curl -LO https://deployer.org/deployer.phar
            - mv deployer.phar /usr/local/bin/dep
            - chmod +x /usr/local/bin/dep
            - dep deploy prod
