image: php:7.2.15

pipelines:
  default:
    - step:
        script:
          - curl -LO https://deployer.org/deployer.phar
          - mv deployer.phar /usr/local/bin/dep
          - chmod +x /usr/local/bin/dep
          - dep deploy prod
