version: "3.1"
services:
  gobie-api-mysql:
    image: mysql:5.7
    container_name: gobie-api-mysql
    working_dir: /application
    volumes:
      - ..:/application
    environment:
      - MYSQL_ROOT_PASSWORD=galinha
      - MYSQL_DATABASE=gobieapi
      - MYSQL_USER=api
      - MYSQL_PASSWORD=galinha
    ports:
      - "8092:3306"

  gobie-api-webserver:
    image: nginx:alpine
    container_name: gobie-api-webserver
    working_dir: /application
    volumes:
      - ..:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8090:80"
    depends_on:
      - gobie-api-php-fpm

  gobie-api-php-fpm:
    build: php-fpm
    container_name: gobie-api-php-fpm
    working_dir: /application
    volumes:
      - ..:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    depends_on:
      - gobie-api-mysql

  gobie-api-mailcatcher:
    image: schickling/mailcatcher
    container_name: gobie-api-mailcatcher
    ports:
      - "8095:1080"

  gobie-api-sqs:
    image: roribio16/alpine-sqs
    container_name: gobie-api-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./sqs/elasticmq.conf:/opt/config/elasticmq.conf
      - ./sqs/sqs-insight.conf:/opt/config/sqs-insight.conf
